apiVersion: v1
kind: Service
metadata:
  annotations:
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
    kapp.k14s.io/identity: v1;my-space/serving.knative.dev/Service/tanzu-java-web-app;serving.knative.dev/v1
    kapp.k14s.io/original: '{"apiVersion":"serving.knative.dev/v1","kind":"Service","metadata":{"annotations":{"kapp.k14s.io/change-rule":"upsert
      after upserting servicebinding.io/ServiceBindings","kbld.k14s.io/images":"null\n","ootb.apps.tanzu.vmware.com/apidescriptor-ref":"true","ootb.apps.tanzu.vmware.com/servicebinding-workload":"true"},"labels":{"app.kubernetes.io/component":"run","app.kubernetes.io/part-of":"tanzu-java-web-app","apps.tanzu.vmware.com/has-tests":"true","apps.tanzu.vmware.com/use-sonarqube":"true","apps.tanzu.vmware.com/workload-type":"web","carto.run/workload-name":"tanzu-java-web-app","kapp.k14s.io/app":"1703828914508853042","kapp.k14s.io/association":"v1.512e806ea626c2bb684d51aa2ca2f646"},"name":"tanzu-java-web-app","namespace":"my-space"},"spec":{"template":{"metadata":{"annotations":{"autoscaling.knative.dev/minScale":"1","boot.spring.io/version":"2.5.8","conventions.carto.run/applied-conventions":"appliveview-sample/app-live-view-appflavour-check\nspring-boot-convention/auto-configure-actuators-check\nspring-boot-convention/spring-boot\nspring-boot-convention/spring-boot-graceful-shutdown\nspring-boot-convention/spring-boot-web\nspring-boot-convention/spring-boot-actuator\nspring-boot-convention/app-live-view-appflavour-check\nspring-boot-convention/app-live-view-connector-boot\nspring-boot-convention/app-live-view-appflavours-boot","developer.conventions/target-containers":"workload"},"labels":{"app.kubernetes.io/component":"run","app.kubernetes.io/part-of":"tanzu-java-web-app","apps.tanzu.vmware.com/auto-configure-actuators":"false","apps.tanzu.vmware.com/has-tests":"true","apps.tanzu.vmware.com/use-sonarqube":"true","apps.tanzu.vmware.com/workload-type":"web","carto.run/workload-name":"tanzu-java-web-app","conventions.carto.run/framework":"spring-boot","tanzu.app.live.view":"true","tanzu.app.live.view.application.actuator.path":"actuator","tanzu.app.live.view.application.actuator.port":"8080","tanzu.app.live.view.application.flavours":"spring-boot","tanzu.app.live.view.application.name":"tanzu-java-web-app"}},"spec":{"containers":[{"env":[{"name":"BP_LOG_LEVEL","value":"DEBUG"},{"name":"JAVA_TOOL_OPTIONS","value":"-Dserver.port=\"8080\"
      -Dserver.shutdown.grace-period=\"24s\""}],"image":"ghcr.io/myminseok/tap-service/minseok-supply-chain/tanzu-java-web-app-my-space@sha256:f7218d529470647d86a174c41fbf6685e59287fa542942eb9fef43078bae6d61","name":"workload","ports":[{"containerPort":8080,"protocol":"TCP"}],"resources":{},"securityContext":{"runAsUser":1000}}],"serviceAccountName":"default"}}}}'
    kapp.k14s.io/original-diff-md5: 23874008fb98810547c24288e7c95c12
    kbld.k14s.io/images: |
      null
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    serving.knative.dev/creator: system:serviceaccount:my-space:default
    serving.knative.dev/lastModifier: system:serviceaccount:my-space:default
  creationTimestamp: "2023-12-29T06:18:51Z"
  labels:
    app.kubernetes.io/component: run
    app.kubernetes.io/part-of: tanzu-java-web-app
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/use-sonarqube: "true"
    apps.tanzu.vmware.com/workload-type: web
    carto.run/workload-name: tanzu-java-web-app
    kapp.k14s.io/app: "1703828914508853042"
    kapp.k14s.io/association: v1.512e806ea626c2bb684d51aa2ca2f646
    serving.knative.dev/route: tanzu-java-web-app
    serving.knative.dev/service: tanzu-java-web-app
  name: tanzu-java-web-app
  namespace: my-space
  ownerReferences:
  - apiVersion: serving.knative.dev/v1
    blockOwnerDeletion: true
    controller: true
    kind: Route
    name: tanzu-java-web-app
    uid: a58e576f-f112-4f9e-ae8a-1aa1e8e86930
  resourceVersion: "2126472"
  uid: aea1e223-1795-4c40-9f8b-2d4dc1c677c8
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  - IPv6
  ipFamilyPolicy: RequireDualStack
  ports:
  - name: http2
    port: 80
    protocol: TCP
    targetPort: 80
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
