apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-web-app
  description: python-web-app
  tags:
    - app-accelerator
    - python
    - web
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=python-web-app'
  links:
    - url: http://tanzu-python-web.apps.tap.lab.pcfdemo.net
      title: tanzu-python-web
      icon: dashboard
spec:
  type: service
  lifecycle: experimental
  owner: default-team
  system: python-web-app
